# Generated by Django 5.0.3 on 2024-04-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to='product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20),
        ),
    ]
